#+TITLE:Haskell Tic Tac Toe Documentation

This application allows you to play Tic Tac Toe on your console. PLEASE use monospace font while playing this game, otherwise it will be completely unusable.

The app is split into four main chunks: Main, Logic, Render and Model. A helper function module exists as well.

* Main

This module runs the program, and provides the necessary set up to get it going.

* Logic

** TODO set up logic for winning the game
** TODO be able to mark the board

* Render

This module provides the necessary function (=drawBoard=) to render the current state of the board to the console.

* Model

This module is a collection of type definitions.
- Game :: The current state of the game. Consists of the board, and the current player.
- Board :: Size of the board (Int) and the current state of the board ([Mark]).
- Mark :: Represents a mark on the board. Consists of a position ((Int, Int)) and a mark type.
- MarkType :: Specifies the character on the board. Either X, O or Empty.
- Position :: X/Y coordinates (x, y).
- Player :: Either player x or player o.
